# Generated by Django 4.1.1 on 2022-09-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0002_funding_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='text',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
