# Generated by Django 4.1.1 on 2022-09-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0003_alter_funding_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='text',
            field=models.TextField(max_length=300),
        ),
    ]
