# Generated by Django 4.1.1 on 2022-09-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='categories',
            field=models.ManyToManyField(related_name='contents', to='categories.category'),
        ),
    ]
