# Generated by Django 4.1.1 on 2022-09-09 22:19

import cloudinary.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_content_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='photo',
        ),
        migrations.AddField(
            model_name='content',
            name='image',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
