# Generated by Django 4.1.1 on 2022-09-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_content_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
