# Generated by Django 4.1.1 on 2022-09-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='owner_name',
            field=models.CharField(default=999, max_length=100),
            preserve_default=False,
        ),
    ]
